# Generated by Django 2.1.13 on 2019-10-09 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_photologue_pro', '0004_auto_20160315_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_photologue_pro_gallery', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='template',
            field=models.CharField(choices=[('cmsplugin_photologue_pro/album_plugin.html', 'Default')], default='cmsplugin_photologue_pro/album_plugin.html', max_length=250, verbose_name='Template'),
        ),
    ]
